version: "3.9"

services:

  db:
    image: postgres:15
    container_name: meeting_ai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meeting_ai
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: meeting_ai_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: meeting_ai
      DB_USER: postgres
      DB_PASSWORD: Yoga@4991
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
